export enum MonsterTypeEnum {
  Aqua = 'Aqua',
  Beast = 'Beast',
  BeastWarrior = 'BeastWarrior',
  Cyberse = 'Cyberse',
  Dinosaur = 'Dinosaur',
  DivineBeast = 'DivineBeast',
  Dragon = 'Dragon',
  Fairy = 'Fairy',
  Fiend = 'Fiend',
  Fish = 'Fish',
  Insect = 'Insect',
  Machine = 'Machine',
  Plant = 'Plant',
  Psychic = 'Psychic',
  Pyro = 'Pyro',
  Reptile = 'Reptile',
  Rock = 'Rock',
  SeaSerpent = 'SeaSerpent',
  Spellcaster = 'Spellcaster',
  Thunder = 'Thunder',
  Warrior = 'Warrior',
  WingedBeast = 'WingedBeast',
  Wyrm = 'Wyrm',
  Zombie = 'Zombie',
}
